### ISSUE TITLE
Register only with username, email address and password

### ISSUE THREAD

**Issue by Waginator** [Waginator/metal-release-radar#11]
**Current situation**
The following information must be entered during the registration process:
- First name
- Surname
- email
- password

**Target**
The first name and last name should be replaced by username. Wherever the email address is currently used, the user name will also be able to be used in the future. This concerns the following functions:
- Login
- Reset password

**Comment by hedgehog1833** [comment]
I have no clue what an "enamel" is but I guess I'll take this one ;-)

**Comment by Waginator** [comment]
Don't know what you talkin' about...
