### ISSUE TITLE
NPE when requested page-parameter value does not exist

### ISSUE THREAD

**Issue by hedgehog1833** [Waginator/metal-release-radar#23]
If you manually request a page for an artist search with a page number that does not exist, an NPE is thrown.

**To Reproduce**
1. Search for an artist: i.e. "Opeth"
2. The result will be two pages
3. Navigate to a non-existings page: /follow-artists?size=25&page=5&artistName=Opeth 

**Expected behavior**
Return 404 View

**Comment by hedgehog1833** [comment]
I pushed something but I'm not really satisfied:
The problem is the 404 is coming from discogs, not our site. If you request a page that does not exist the ResponseEntity coming from discogs still contains a non-null ArtistSearchResults-Instance. But the Pagination and the list of ArtistSearchResult-Objects are null.
So what I did is "manually" check the ResponseEntity for its http status code and then in case return our 404 page. Is this the way to go? Or should the CustomErrorController handle this? Or no 404 end a message for "invalid page number"?
Also: I haven't really found out when the call to getBody() of the ResponseEntity can return null. IntelliJ warns about it but neither an empty search, the 404, no results or anything else was able to reproduce this. So I'm not sure if the null-check is really necessary.

**Comment by Waginator** [comment]
I don't think we should be working with 404 on our side. 

It depends on the REST API on the other side (Discogs in our case) whether the body can be null or not. It seems that Discogs writes always data in the HTTP body.

My suggestion for a solution is:
- We work again with Optional in the RestClient
- If the body is null or response code is != OK, then we return an empty Optional. That would also protect us against Bad Request. 
- If the status is not OK, then we log this as a warning.
- If the result is an empty Optional, a message is displayed in the UI below the search input, e.g. "No data can be displayed for the query parameters" or something like that...

I also pushed a little commit to your branch. Please look at the diff. A note about methods that start with `getXXX()`. I would only use the prefix `get` for actual getter methods. For methods that start with `get`, we expect (without knowing the exact implementation) that it is not a complex operation that branches to other methods or do some other calculations/transformations.
