### ISSUE TITLE
Improve pagination

### ISSUE THREAD

**Issue by Waginator** [Waginator/metal-release-radar#47]
**Current situation**
- Our current pagination layout needs improvement

**Target**
- build pagination DTO class for easy reuse (see https://github.com/Waginator/SpringBootBlueprint/blob/master/src/main/java/com/wagner/blueprint/web/mvc/EmployeesController.java)
- Use Bootstrap Pagination Layout (https://getbootstrap.com/docs/4.3/components/pagination/)
- right arrangement
- Indicator for the current page
- Previous/Next should be disabled accordingly, not hidden

**Comment by hedgehog1833** [comment]
Closed with #85
