### ISSUE TITLE
Improve test coverage and test infrastructure

### ISSUE THREAD

**Issue by Waginator** [Waginator/metal-release-radar#48]
- Use AssertJ instead of JUnit Assertions
- Create execution configurations for "Execute all unit tests", "Execute all integration tests" and "Execute all tests"
- The execution configurations should be automatically created using a small script or Maven Goal
- Use Maven Failsafe Plugin for Integration tests
- Configure Maven Surefire-Report Plugin

**Comment by hedgehog1833** [comment]
implemented with #59
