### ISSUE TITLE
Refactoring of properties for database access, mail account and security

### ISSUE THREAD

**Issue by Waginator** [Waginator/metal-release-radar#53]
**Current situation**
The access data for the database and the mail server as well as other security-relevant information are stored in .properties files.

**Target**
All information that grants access to a third party system or is relevant to security (such as API secrets) should be available to the application as environment variables. 

The existing properties in the .properties files are retained, but then there is something like this:
`discogs.access-token=${DISCOGS.ACCESS_TOKEN}`

**Comment by hedgehog1833** [comment]
implemented with #61
